"""Type stubs for the aufbau native module (pyo3)."""

from typing import Optional

Symbol = tuple[str, str, Optional[str]]
"""A grammar symbol: (kind, value, binding) with kind one of "nt" | "lit" | "re"."""

Production = tuple[str, Optional[str], list[list[Symbol]]]
"""A nonterminal definition: (name, rule, alternatives)."""

Rule = tuple[str, str, str]
"""A typing rule in inference notation: (name, premises, conclusion)."""

class Term:
    def label(self) -> Optional[str]: ...
    def children(self) -> list[Term]: ...
    def is_var(self) -> bool: ...
    def is_leaf(self) -> bool: ...
    def is_con(self) -> bool: ...
    def is_ground(self) -> bool: ...

class SPG:
    def __init__(self, source: str) -> None: ...
    @staticmethod
    def build(
        productions: list[Production],
        rules: list[Rule] = ...,
        rewrites: list[tuple[str, str]] = ...,
        start: Optional[str] = ...,
        ty: Optional[str] = ...,
    ) -> SPG: ...
    def source(self) -> str: ...
    start: Optional[str]
    def nonterminals(self) -> list[str]: ...
    def productions(self, nt: str) -> list: ...
    def nt_rule(self, nt: str) -> Optional[str]: ...
    def rule_names(self) -> list[str]: ...
    def is_transparent(self, nt: str) -> bool: ...
    def specials(self) -> list[str]: ...
    def tokenize(self, input: str) -> list: ...
    def parse_type(self, s: str) -> Term: ...
    def show(self, t: Term) -> str: ...
    def normalize(self, s: str) -> Term: ...
    def unify(self, a: str, b: str) -> Optional[dict[str, str]]: ...
    def unify_modulo(self, a: str, b: str) -> Optional[dict[str, str]]: ...
    def rewrites(self) -> list[tuple[str, str]]: ...
    def signature(self) -> list[tuple[str, int]]: ...
    def completeness(self) -> tuple[str, list[str]]: ...

class Synthesizer:
    def __init__(self, spec_source: str, input: str = "") -> None: ...
    @staticmethod
    def from_grammar(grammar: SPG, input: str = "") -> Synthesizer: ...
    def set_input(self, input: str) -> None: ...
    def input(self) -> str: ...
    def parse(self) -> str: ...
    def feed(self, token: str) -> str: ...
    def try_feed(self, token: str) -> str: ...
    def mask(self, candidates: list[str]) -> list[bool]: ...
    def in_scope(self, expected: Optional[str] = ...) -> list[str]: ...
    def status(self) -> str: ...
    def root_type(self) -> Optional[Term]: ...
    def add_to_ctx(self, name: str, ty: str) -> None: ...
    def clear_ctx(self) -> None: ...
    def is_complete(self) -> bool: ...
    def grammar(self) -> SPG: ...
    def get_rule(self, name: str): ...
    def ast(self): ...

class Regex:
    def __init__(self, pattern: str) -> None: ...
    def matches(self, text: str) -> bool: ...
    def prefix_match(self, prefix: str) -> PrefixStatus: ...
    def derivative(self, text: str) -> Regex: ...
    def deriv(self, character: str) -> Regex: ...
    def is_empty(self) -> bool: ...
    def is_nullable(self) -> bool: ...
    def match_len(self, text: str) -> Optional[int]: ...
    def to_pattern(self) -> str: ...

class PrefixStatus:
    kind: str
    regex: Optional[Regex]
    def is_complete(self) -> bool: ...
    def is_prefix(self) -> bool: ...
    def is_extensible(self) -> bool: ...
    def is_no_match(self) -> bool: ...
